# Find the following inverses:

(First try it by hand and then use numpy to validate your answers)

In [4]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
ainv = (np.linalg.inv(a))

print(ainv)
# find a^-1

b = np.eye(2)
binv = (np.linalg.inv(b))
print(binv)

# find b^-1

c = np.zeros([2,2])
print(c)
cinv = np.linalg.inv(c)
print(cinv)

# find c^-1 if you can

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]


LinAlgError: Singular matrix

# Find the transposes of the following matrices:

(Again, first try it by hand and then use numpy to validate your answers)

$$\begin{bmatrix}1 & 2 & 3 & 4 & 5\\ 6 & 7 & 8 & 9 & 10\end{bmatrix}$$

Try generating this matrix without actually typing it in, use the `arange()` and `reshape` functions to generate this matrix for you.

In [7]:
p = np.arange(1,11)
print(p)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
p = p.reshape(2,5)
print(p)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
p = np.matrix.transpose(p)
print(p)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


# Try to figure out the output of the following codes:

In [21]:
p = np.arange(1,11).reshape(2,5).transpose()
print(p)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [23]:
b = np.arange(10).reshape(2,5) #array-range => arange
print(b.transpose())

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


# Try to figure out what the following code does:

Some parts of the following code weren't covered in class. Try understanding how these functions work by yourself. We will discuss these in class again, but I want everyone to try these out since I strongly believe that what you learn through self-learning will remain much very strongly embedded in your mind than when you learn it from someone else:

In [30]:
q = np.repeat(50,10)
print(q)

q1 = q.reshape(2,-1)
print(q1)

#  1*10 => 2rows => 5 columns

[50 50 50 50 50 50 50 50 50 50]
[[50 50 50 50 50]
 [50 50 50 50 50]]


<details>
  <summary>How repeat(a,n) works:</summary>
    <p>
    Basically, repeat(a,n) creates a $1\times n$ matrix and each element is set to $a$.
    </p>
</details>

<details>
  <summary>How reshape(a,-1) or reshape(-1,a) works:</summary>
    <p>
    If you want to fix the number of rows and want the columns to adjust automatically, then you use -1. As you see in the example, if you use reshape(2,-1), it basically makes sure that there are 2 rows, and changes the columns to 5 accordingly.
    </p>
</details>

So now, the next one should be clear. Try it yourself:

In [31]:
p = np.arange(1,11).reshape(2,-1)
print(p)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Using Matrices for solving a set of Linear Equations:

One Major usage of Matrices is to solve Linear Equations. This is extremely uesful for linear programming optimization problems and other similar things, and you can definitely use this technique for various daily math problems.

On doing the matrix computation below, you will see that it is the same as the 2 linear equations $a_1 x + b_1 y = c_1$ and $a_2 x + b_2 y = c_2$.

$\begin{bmatrix} a_1 & b_1 \\ a_2 & b_2 \end{bmatrix} \times \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix}c_1\\c_2\end{bmatrix} = \begin{bmatrix}a_1 x + b_1 y \\ a_2 x + b_2 y \end{bmatrix}$

Now, if we want the value of $\begin{bmatrix} x \\ y \end{bmatrix}$, we need to premultiply both sides of this equation with the inverse of the first matrix:

$\begin{bmatrix} a_1 & b_1 \\ a_2 & b_2 \end{bmatrix}^{-1} \times \begin{bmatrix} a_1 & b_1 \\ a_2 & b_2 \end{bmatrix} \times \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} a_1 & b_1 \\ a_2 & b_2 \end{bmatrix}^{-1} \times\begin{bmatrix}c_1\\c_2\end{bmatrix} = \begin{bmatrix} x \\ y \end{bmatrix}$

Hence, solving linear equations now becomes a simple task of just multiplying matrices! No more "add this equation to that equation", and definitely fewer silly mistakes.

Now, you will need to take some inputs from the user and create a linear equation solver.

See the User interaction below:

```
Enter the value of a1 for a1x+b1y=c1: 1
Enter the value of b1 for a1x+b1y=c1: 0
Enter the value of c1 for a1x+b1y=c1: 1
Enter the value of a2 for a2x+b2y=c2: 0
Enter the value of b2 for a2x+b2y=c2: 1
Enter the value of c2 for a2x+b2y=c2: 1
The values of x and y are respectively: 
 [[1.]
 [1.]]
```

<details>
  <summary>Solution (don't look until you solve!)</summary>
  
  ```python
  a1 = float(input("Enter the value of a1 for a1x+b1y=c1: "))
  b1 = float(input("Enter the value of b1 for a1x+b1y=c1: "))
  c1 = float(input("Enter the value of c1 for a1x+b1y=c1: "))
  a2 = float(input("Enter the value of a2 for a2x+b2y=c2: "))
  b2 = float(input("Enter the value of b2 for a2x+b2y=c2: "))
  c2 = float(input("Enter the value of c2 for a2x+b2y=c2: "))
  inv1 = np.linalg.inv([[a1,b1],[a2,b2]])
  xy = inv1 @ np.array([[c1],[c2]])
  print("The values of x and y are respectively: \n",xy)
  ```

</details>

In [32]:
a1 = float(input("Enter the value of a1 for a1x+b1y=c1: "))
b1 = float(input("Enter the value of b1 for a1x+b1y=c1: "))
c1 = float(input("Enter the value of c1 for a1x+b1y=c1: "))
a2 = float(input("Enter the value of a2 for a2x+b2y=c2: "))
b2 = float(input("Enter the value of b2 for a2x+b2y=c2: "))
c2 = float(input("Enter the value of c2 for a2x+b2y=c2: "))
inv1 = np.linalg.inv([[a1,b1],[a2,b2]])
xy = inv1 @ np.array([[c1],[c2]])
print("The values of x and y are respectively: \n",xy)

Enter the value of a1 for a1x+b1y=c1: 1
Enter the value of b1 for a1x+b1y=c1: 2
Enter the value of c1 for a1x+b1y=c1: 3
Enter the value of a2 for a2x+b2y=c2: 2
Enter the value of b2 for a2x+b2y=c2: 1
Enter the value of c2 for a2x+b2y=c2: 4
The values of x and y are respectively: 
 [[1.66666667]
 [0.66666667]]


In [5]:
o = np.array([[1,1],[2,2]])

In [6]:
u = np.linalg.inv(o)

LinAlgError: Singular matrix