In [3]:
import numpy as np

b = np.array([[4,-2],[4,0]])
c = np.array([[-2,-2],[1,-3]])
a = (c - b)/3

print(a)

[[-2.  0.]
 [-1. -1.]]


In [4]:
A = np.array([[1,4,-7],[8,6,0]])
B = np.array([[7,6,2],[1,5,3]])

print(A + 2 * B)
print(B - 2 * A)

[[15 16 -3]
 [10 16  6]]
[[  5  -2  16]
 [-15  -7   3]]


In [7]:
A_2 = np.array([[0,4,6],[3,0,-1]])
B_2 = np.array([[0,1],[-1,2],[-5,-6]])

#print(A_2 * B_2)
print(A_2 @ B_2)

[[-34 -28]
 [  5   9]]


In [8]:
print(A*B)

[[  7  24 -14]
 [  8  30   0]]


In [10]:
I = np.eye(3)
print(A_2 @ I)

[[ 0.  4.  6.]
 [ 3.  0. -1.]]


In [11]:
I2 = np.eye(2)
print(I2 @ A_2)

[[ 0.  4.  6.]
 [ 3.  0. -1.]]


In [12]:
print(I)
print(I2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]]


In [13]:
print(I @ B_2)

[[ 0.  1.]
 [-1.  2.]
 [-5. -6.]]


In [14]:
import matplotlib.pyplot as plt

import scipy

In [16]:
p = np.array([[3,4],[0,0]])
q = np.array([[9,16],[0,1]])

print(p @ p)
print(q)

print(p @ p == q)

[[ 9 12]
 [ 0  0]]
[[ 9 16]
 [ 0  1]]
[[ True False]
 [ True False]]
