# Transpose of a matrix

When we write the rows of a matrix as its columns and the columns as its rows, then it is called the Transpose of the matrix.

If $A = \begin{bmatrix}1 & 2 & 3 & 4\\ 5 & 6 & 7 & 8\end{bmatrix}$, then $A^T = \begin{bmatrix}1 & 5 \\ 2 & 6\\ 3 & 7 \\ 4 & 8\end{bmatrix}$

To achieve this, we can use the `numpy.matrix.transpose` function.

In [1]:
import numpy as np
A = np.array([[1,2,3,4],[5,6,7,8]])
print(np.matrix.transpose(A))

print(A.transpose())

print(A.T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


# Inverse of a Matrix

$A = \begin{bmatrix} 12 & 10 \\ 11 & 13\end{bmatrix}$

$A \times A^{-1} = I$

In [2]:
print(np.eye(2))

A = np.array([[12,10],[11,13]])

print(1/A)

[[1. 0.]
 [0. 1.]]
[[0.08333333 0.1       ]
 [0.09090909 0.07692308]]


In [3]:
print(1/12)
print(1/11)
print(1/13)

0.08333333333333333
0.09090909090909091
0.07692307692307693


In [5]:
C = 1/A
print(A @ C)

[[1.90909091 1.96923077]
 [2.09848485 2.1       ]]


In [8]:
Ainv = np.linalg.inv(A)
print(Ainv)

print(Ainv @ A)

[[ 0.2826087  -0.2173913 ]
 [-0.23913043  0.26086957]]
[[ 1.00000000e+00  4.71844785e-16]
 [-1.11022302e-16  1.00000000e+00]]


In [9]:
a = 13/46
print(a)

0.2826086956521739


In [10]:
c = -11/46
print(c)

-0.2391304347826087


In [11]:
print(A @ Ainv)

[[1.00000000e+00 2.22044605e-16]
 [2.22044605e-16 1.00000000e+00]]


In [12]:
print(6.023 * 10**23 == 6.023e23)

False


In [13]:
print(6.023*10**23)

6.022999999999999e+23


In [14]:
print(6.023e23)

6.023e+23


In [15]:
print(np.linalg.inv([[1,2],[2,1]]))

[[-0.33333333  0.66666667]
 [ 0.66666667 -0.33333333]]


In [16]:
np.set_printoptions(precision=54)

In [17]:
print(np.linalg.inv([[1,2],[2,1]]))

[[-0.3333333333333333  0.6666666666666666]
 [ 0.6666666666666666 -0.3333333333333333]]


In [19]:
A.reshape(1,4)

array([[12, 10, 11, 13]])

In [20]:
print(A)

[[12 10]
 [11 13]]


In [21]:
A.reshape(4,1)

print(type(A))

<class 'numpy.ndarray'>


In [33]:
d = list(range(10, 0, -1))
x = np.arange(10, 0, -1)

In [36]:
print(d)
print(x)

print(type(d))
print(type(x))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[10  9  8  7  6  5  4  3  2  1]
<class 'list'>
<class 'numpy.ndarray'>


In [38]:
print(np.zeros([3,4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
print(np.matrix([[1,2],[3,4]]))
print(type(np.matrix([[1,2],[3,4]])))

[[1 2]
 [3 4]]
<class 'numpy.matrix'>


In [41]:
print(np.mean(x))

5.5


In [42]:
g = np.linalg.inv([[1,2],[2,1]])
print(np.mean(g))

0.16666666666666669
