# Common Excel tasks demonstrated in NumPy

In [1]:
import numpy as np

## Mean of a list/array:

In [2]:
x = np.arange(1,1001)
print(np.mean(x))

500.5


## Sum of a list/array:

In [6]:
npsum = np.sum(np.arange(1,101))
print(npsum)

npsum2 = np.sum(np.repeat(2,100))
print(npsum2)

s = np.arange(1,101).reshape(10,10)
print(s)
print(np.sum(s))

5050
200
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
5050


## Rounding off all elements of a list/array:

In [8]:
unrounded = np.random.uniform(10,20,[3,3])
print("Before rounding:\n",unrounded)

# rounding it to the nearest integer
roundedint = np.around(unrounded, decimals = 0) # array round
print("\nNearest integer:\n",roundedint)

# rounding it off to 3 decimal points:
rounded3dp = np.around(unrounded, decimals = 3)
print("\n3 decimal points:\n",rounded3dp)

# rounding it off to nearest 10s:
rounded10s = np.around(unrounded, decimals = -1)
print("\nNearest 10s:\n",rounded10s)

Before rounding:
 [[12.06544071 11.357109   16.41986226]
 [12.95729909 15.33178946 15.33591147]
 [15.15483045 12.82748635 16.48868613]]

Nearest integer:
 [[12. 11. 16.]
 [13. 15. 15.]
 [15. 13. 16.]]

3 decimal points:
 [[12.065 11.357 16.42 ]
 [12.957 15.332 15.336]
 [15.155 12.827 16.489]]

Nearest 10s:
 [[10. 10. 20.]
 [10. 20. 20.]
 [20. 10. 20.]]


## Generating random data (floating point values):

### 1. Generating random data according to required dimensions: 

`np.random.rand(d0,d1,...,dn)`

<sub>The dimensions are represented as d0, d1, d2... till dn, we can have as many dimensions as we want</sub>

In [10]:
x = np.random.rand(2,3,4) #since we specified 3 numbers, the array produced will be 3-dimensional
print(x)

[[[0.28330738 0.38133298 0.83087685 0.82183063]
  [0.06496599 0.23133559 0.36583783 0.8233732 ]
  [0.82237859 0.76746353 0.82928986 0.45802221]]

 [[0.43815622 0.7456136  0.41920555 0.00619271]
  [0.50612402 0.18223348 0.29883527 0.01506173]
  [0.98614652 0.00263806 0.90343806 0.9752827 ]]]


In [12]:
y = np.random.rand(2,2,2,2) # now you will see a 4-dimesional array:
print(y)

[[[[0.50694116 0.52617421]
   [0.7869556  0.67278175]]

  [[0.80726536 0.15646814]
   [0.3313481  0.25973283]]]


 [[[0.45460851 0.79172336]
   [0.95259442 0.99163249]]

  [[0.59793404 0.48100966]
   [0.79274651 0.46079027]]]]


### 2. Sampling random data from a **normal distribution** according to required dimensions: 

`np.random.randn(d0,d1,...,dn)`

In [14]:
z = np.random.randn(5,4)
print(z)

print(np.mean(z))

[[-0.69545273 -0.54190204  0.04204518  0.00465097]
 [-0.05337873 -0.5951939   0.26844583  0.02736163]
 [-0.34839288  1.05588972  1.27466176 -0.03912463]
 [-0.21496313 -1.92344064 -0.59653141 -0.54327264]
 [ 0.1944348   1.17660987  1.12904289  2.08237534]]
0.08519326200613142


### 3. Generate random integers from low (inclusive) to high (exclusive): 

`np.randint(low[, high, size, dtype])` 

<sub>(the parameters in square brackets are optional)</sub>

According to the [official numpy documentation](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html):

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval \[low, high). If high is None (the default), then results are from \[0, low).

In [19]:
w = np.random.randint(256)
print(w)

153


In [24]:
v = np.random.randint(128,256) #returns a single int between 128 and 256 (256 excluded)
print(v)

224


In [25]:
u = np.random.randint(128,256,size = [12,3,4]) # returns a 12*3*4 3D array populated with numbers from 128 to 256 (256 excluded)

# this is the same as writing np.random.randint(128,256,[12,3,4]) or np.random.randint(128,256,(12,3,4))
# We normally write `size = [...]` so as to make it clear to the user what we are trying to achieve. 
# We may even write `low=128, high=256` and so on if we want to, but that's up to us if we want the code to be even more clear.
print(u)

[[[155 240 178 192]
  [166 142 160 154]
  [254 165 212 154]]

 [[187 226 189 210]
  [233 161 214 254]
  [156 182 198 193]]

 [[140 138 177 230]
  [232 208 133 232]
  [175 227 235 220]]

 [[211 255 214 180]
  [197 225 128 147]
  [252 253 224 182]]

 [[241 152 166 195]
  [254 228 212 234]
  [229 237 170 145]]

 [[169 190 240 145]
  [187 213 165 203]
  [193 188 239 227]]

 [[200 186 234 205]
  [172 160 228 175]
  [160 145 216 246]]

 [[160 249 228 141]
  [154 254 158 230]
  [221 181 237 180]]

 [[199 177 152 182]
  [140 236 228 136]
  [227 217 191 244]]

 [[198 248 179 166]
  [199 189 243 164]
  [248 227 175 161]]

 [[188 219 134 221]
  [241 201 169 134]
  [132 207 156 237]]

 [[173 186 231 212]
  [223 196 210 130]
  [175 218 167 176]]]


In [31]:
dtypeex = np.random.randint(128,256,size=[3,4],dtype='int32')
print(dtypeex)

[[155 180 213 235]
 [129 168 153 139]
 [211 204 170 227]]


The `dtype` is basically the data type. You may be wondering, if we are already using `int`, then what is the use of a data type?

The thing is, numpy actually has a lot more data types (np.int, np.int32, np.int64, and long_int, etc.) which are more exact representations of int in the memory. This option enables us to choose this, but it is not used generally, unless we have a very low memory budget.

### 3.1 Generate random integers of a fixed data type:

`np.random.random_integers(low[, high, size])` => Same as the previous function except we can't choose the datatype, which is set to `np.int` by default.

It is deprecated (i.e. no longer supported) in the latest version of numpy, which is why I get the warning below:

In [26]:
t = np.random.random_integers(0,12,[3,4])

/home/abhigyan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 12 + 1) instead
  """Entry point for launching an IPython kernel.


### 4. Generate random floats in the half-open interval \[0.0,1.0):

<sub>Half open means that 0.0 is included but 1.0 is excluded</sub>

`np.random.ranf([size])` or 
`np.random.random_sample([size])` or 
`np.random.random([size])` or 
`np.random.sample([size])`

(This time, python provides 4 ways of achieving the exact same result... Kinda silly in my opinion, but maybe there's a deeper reason we don't understand yet)

In [32]:
p = np.random.ranf() # if you skip the [size] parameter, then it just returns a single value. 
# Try it out in the other ones by yourself
print(p)
q = np.random.random([2,3])
print(q)
r = np.random.random_sample([2,3])
print(r)
s = np.random.sample([2,3])
print(s)

0.0030537178642814355
[[0.81209879 0.60242043 0.83010351]
 [0.97065229 0.78155169 0.24787665]]
[[0.87701759 0.67727621 0.43267668]
 [0.55826618 0.36070767 0.40046248]]
[[0.15956314 0.4679746  0.91486154]
 [0.13070212 0.9603646  0.79049235]]


### 5. Generate random floats in a chosen interval:

`np.random.uniform(start, stop, [size])`

In [37]:
ubiquity = np.random.uniform(-10,100, [2,5])
print(ubiquity)

ubiquity2 = 100*np.random.ranf([2,5])
print(ubiquity2)

[[39.19448391  4.3300741  34.00385909 22.10522948 87.64393126]
 [48.8587886  40.8844031  85.4685101  29.37359622 73.94492133]]
[[81.33350253 93.5185062  34.39636715  4.29191106 80.50803482]
 [72.59846534 14.87224422 29.31082992 82.40902121 78.25529668]]


### 6. Choose one number randomly from a list of numbers you enter yourself:

`np.random.choice(a[, size, replace, p])`

`a`: The array you want to choose values from. If you enter a single int `n`, then it will treat it as the array `arange(n)`.

`size`: The shape of the output array

`replace`: Whether you don't mind getting the same values again (if replace=True, you may get the same numbers more than once, else you will get each number only once)

`p`: The probability associated with each element: So if you want one element to occur more often than the others, you basically use the `p` array. The size of the `p` array must be the same as that of the `a` array.

In [41]:
l = np.random.choice(np.arange(2,13))
print(l) # it will choose a single number from the arange(0,12)

# 2 = 1 + 1
# 3 = 1 + 2 or 2 + 1
# 4 = 1 + 3 or 2 + 2 or 3 + 1
# 7 = 1 + 6 or 2 + 5 or 3 + 4 or 4 + 3 or 5 + 2 or 6 + 1
# 8 = 2 + 6 or 3+5 or 4+4 or 5+3 or 6+2

3


In [42]:
m = np.random.choice([123,12,1,0],size = [2,4])
print(m)

[[  1 123   0  12]
 [  0 123   0 123]]


In [45]:
n = np.random.choice([123,12,1,0,45,65,78,90.5,"Hi"],size=[2,2], replace=True)
print(n)

o = np.random.choice([123,12,1,0,45,65,78,90.5,"Hi"],size=[2,2], replace=False)
print(o)

tambola = np.random.choice(100,size=[100],replace = False)
print(tambola)

[['45' '65']
 ['45' '123']]
[['45' '1']
 ['123' '65']]
[47 75 43  9  4 17 25 60 82 18 36 88 56 64 81 51 72  1 68 34 89  5 37 11
 55 65 13 70 59 96  0 20  6 41 58 19 97 26 49 53 63 44 15  8 30 62  2 84
 40 27 77 94 91  7 21 76 74 45 10 24 85 83 32 35 38 99 39 57 95 86 92 80
 71 73 23  3 46 67 28 50 48 16 52 22 79 29 12 66 14 78 61 90 54 42 87 31
 33 69 93 98]


### 7. Shuffle a sequence:

`np.random.shuffle(X)`

In [48]:
a = np.arange(20)
print(a)
np.random.shuffle(a)
print(a)

tambola = np.arange(100)

np.random.shuffle(tambola)

print(tambola)
# You could use this to shuffle your music if you use it along with the ffmpeg library, definitely go check it out!

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 8  0 12 13 18 11  2 16  5 17  3 19  1 10 14  9  6  4 15  7]
[ 3 84 83 28 74 17 56 21 63 50 80 90 92 57 93 81 71 94 78 12 82 41 98 66
 89 11 85 24 91 79 36 45 13 27 62  2 16 97 39 58 52 26  1  7 75 30 15 10
 20 46 60 47 35 22 64 33 69  8 25 67 73 48 42 87 68 23 53 54 88 18 32 86
 96 40 37 14 31  6 59 65  9 99  5 61 72 51 55 70 29 77 76  0 19  4 95 43
 49 34 44 38]
