# Day 8 - Introduction to Matrices and Linear Algebra using NumPy

What is a matrix?

Matrices (plural of matrix) are **rectangular arrangements of numbers**.

### Some examples:

1. $\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 3\end{bmatrix}$
2. $\begin{bmatrix}100 & -99 \\78 & -918 \\2 & 9000 \\10 & 4\end{bmatrix}$

3. $\begin{bmatrix}2 & 3 & 100 & -100 & 80 & 6\end{bmatrix}$

4. $\begin{bmatrix}12\\3\\4\\67\\1\end{bmatrix}$


### Not a matrix:
$$\begin{bmatrix}
100 & -99 & 80\\
78 & -918 \\
2 & 9000 & 100 & 200\\
10 & 4 \\
 & 10
\end{bmatrix}
$$

(It is not a matrix because it does not have the same number of elements in each row/collumn)

Age  Ht.
________
18   5.5
15   6.5
13   5.2
26   5.7
80   5.0
65   4.0
45   8.0

Age  18  15  13
ht. 5.5 6.5 5.2

NumPy => Numerical Python (Support for Linear Algebra and Matrices)

In [7]:
import numpy as np

In [3]:
A = np.array([[3,4,5],[1,2,3]])


a = [[3,4,5],[1,2,3]]
print(A)
print(type(A))

print(a)
print(type(a))

[[3 4 5]
 [1 2 3]]
<class 'numpy.ndarray'>
[[3, 4, 5], [1, 2, 3]]
<class 'list'>


## Rows and Columns:

Basically, each horizontal set of numbers is called a row, and each vertical set of numbers is called a column.

If a matrix has only one row, it is called a **row matrix**, and if it has only one column, then it is called a **column matrix**.

Example **3** above is a **row matrix**, while example **4** is a **column matrix**.

## Order of a Matrix:

The order of a matrix is basically a measure of the rows and the columns of it. If a matrix has 3 rows and 4 columns, then it is said to be a $3\times4$ matrix (and it is read as **3 by 4** matrix)

In general, if a matrix has $n$ rows and $m$ columns, its order is $n\times m$

If the number of rows and columns are both equal to $n$, then the matrix is said to be a **square matrix** of order $n$.

In [10]:
print(np.shape(A))

print(np)
print(type(np))

print(np.shape(A))

print(np.ndim(A))

(2, 3)
<module 'numpy' from '/home/abhigyan/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
<class 'module'>
(2, 3)
2


In [13]:
p = np.array([[[12,12,10,10],[11,10,1,90],[90,10,3,70]],[[-90,-80,-70,80],[918,126,458,80],[80,70,60,80]]])
print(np.ndim(p))
print(np.shape(p))

3
(2, 3, 4)


12 12 10 10           12 12 10 11
11 10  1 90           11 10  1 90
90 10  3 70           

-90 -80 -70 80
918 126 458 80
 80  70  60 80

## Sum and Difference of Matrices:

If 2 matrices are of the same order, then we can add (or subtract) them element wise.

### Addition:

$\begin{bmatrix}
  a & b\\
  c & d
\end{bmatrix} + \begin{bmatrix}
  e & f\\
  g & h 
\end{bmatrix} = \begin{bmatrix}
  a+e & b+f\\
  c+g & d+h
\end{bmatrix}$

### Subtraction: (Same as addition, but with a negative sign)

$\begin{bmatrix}
  a & b\\
  c & d
\end{bmatrix} - \begin{bmatrix}
  e & f\\
  g & h
\end{bmatrix} = \begin{bmatrix}
  a-e & b-f\\
  c-g & d-h
\end{bmatrix}$


### Example:

1. Addition:

$\begin{bmatrix}
  3 & 4 & 7 & 8\\
  0 & 0 & 0 & 0
\end{bmatrix} + \begin{bmatrix}
  12 & 13 & -14 & 15\\
  9 & 9 & 8 & 7
\end{bmatrix} = \begin{bmatrix}
  15 & 17 & -7 & 23\\
  9 & 9 & 8 & 7
\end{bmatrix}$

2. Subtraction:

$\begin{bmatrix}
  3  & 8\\
  0  & 0\\
  1  & 4
\end{bmatrix} - \begin{bmatrix}
  12 & 15\\
  9 & 7\\
  12 & -8
\end{bmatrix} = \begin{bmatrix}
  -9 & -7\\
  -9 & -7\\
  -11 & 12
\end{bmatrix}$

In [25]:
q = np.array([[3,4,7,8],[0,0,0,0]])
r = np.array([[12,13,-14,15],[9,9,8,7]])

#print(np.shape(r))
#print(q)
#print(r)

print(q+r)
print(np.add(q,r))

a = np.array([[3,8],[0,0],[1,4]])
b = np.array([[12,15],[9,7],[12,-8]])

#print(a-b)

[[15 17 -7 23]
 [ 9  9  8  7]]
[[15 17 -7 23]
 [ 9  9  8  7]]


## Multiplication by a single number (aka a *scalar*)

We can multiply every element of a matrix with a single number (known as a scalar). This number may be positive, negative, or even be a variable, but it should not be a matrix. There are different rules for multiplying matrices.

Example:

$12 \times \begin{bmatrix}
  3 & 4 & 7 & 8\\
  0 & 0 & 0 & 0
\end{bmatrix} = \begin{bmatrix}
  36 & 48 & 84 & 96\\
  0 & 0 & 0 & 0
\end{bmatrix}$

Now, how do we do this multiplication? Let's see:

In [28]:
print(q/100)

[[0.03 0.04 0.07 0.08]
 [0.   0.   0.   0.  ]]


## Multiplying a matrix with another matrix:

All matrices can't be multiplied with each other... The product AxB and BxA are also not the same thing in Matrices. There are various rules to be followed here:

For 2 matrices to be compatible for multiplication, the number of columns of the first matrix need to be equal to the number of rows of the second matrix.

I.e.: If we have 2 matrices $A$ and $B$ of order $a\times b$ and $c\times d$ respectively, then for the multiplication $A\times B$ to be possible, $b = c$. 

And, if we want the reverse multiplication to be possible, $B \times A$, then $a = d$.

Now, let us go through a few examples:

1. This matrix multiplication is not feasible, because the first matrix has 4 columns but the second matrix has 2 rows...
$\begin{bmatrix}
  3 & 4 & 7 & 8\\
  0 & 0 & 0 & 0
\end{bmatrix} \times \begin{bmatrix}
  12 & 13 & -14 & 15\\
  9 & 9 & 8 & 7
\end{bmatrix}$

2. This matrix multiplication is also not possible because the number of columns of the first (4) is not equal to the number of rows of the second (6)

$\begin{bmatrix}
  3 & 4 & 7 & 8\\
  0 & 0 & 0 & 0
\end{bmatrix} \times \begin{bmatrix}
  12 & 13 \\
  9 & 9 \\
  1 & 1 \\
  2 & -2 \\
  78 & -7 \\
  1 & 2
\end{bmatrix}$

3. This matrix multiplication is actually possible:

$\begin{bmatrix}
  3 & 4 & 7 & 8\\
  0 & 0 & 0 & 0
\end{bmatrix} \times \begin{bmatrix}
  12 & 13 \\
  9 & 9 \\
  1 & 1 \\
  2 & -2 \\
\end{bmatrix} = \begin{bmatrix}
  95 & 98\\
  0 & 0
\end{bmatrix}$


## Tensors: Basically, multi-dimensional Matrices

Sometimes, we need more than just the 2-dimensional arrangement of numbers which matrices provide. 

For example, coloured images (RGB) which you can see are saved as 3 matrices piled one on top of the other, thus making it 3-dimensional. (See the image)

In some cases, the number of dimensions exceeds 3, and then most humans aren't able to imagine them (trust me, we won't be going there, so this much will be enough).

I'm introducing these Tensors to you because NumPy does all its stuff in terms of multi-dimensional matrices (not limited to mere 2 or 3 dimensions), which becomes very useful when you use certain datasets. We will also use some such datasets in the days to come, but for now, we will stick to 2D (and at most 3D matrices).

Example: ![image.png](attachment:image.png)

In [29]:
print(3+8+15)

26


In [30]:
print(p@q)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)