# Some More NumPy Functions:

## Extract the odd numbers from a numpy array and display them (don't use a for-loop)

In [1]:
import numpy as np
arr = np.arange(1,11)
print(arr)
print(arr[arr%2==1])

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [2]:
arr = np.arange(1,11)

arr[ arr%2 == 1] += 2

print(arr)

[ 3  2  5  4  7  6  9  8 11 10]


## Stack arrays a and b vertically

In [3]:
a = np.arange(1,11).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

print(np.vstack([a,b]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  1  1  1  1]
 [ 1  1  1  1  1]]


## Stack arrays a and b horizontally.

In [4]:
print(np.hstack([a,b]))

[[ 1  2  3  4  5  1  1  1  1  1]
 [ 6  7  8  9 10  1  1  1  1  1]]


In [5]:
np.set_printoptions(threshold = 10000000)

## Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

`a = np.array([1,2,3])`

`out = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`

In [6]:
a = np.array(range(1,4))
# a = np.arange(1,4)
amid = np.repeat(a,3)
print(amid)

atile = np.tile(a,3)
print(atile)

out = np.hstack([amid,atile])
print(out)


#out = np.concatenate([amid,atile], axis=0)
print(out)

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## Create a 2D array of shape 5×3 to contain random decimal numbers between 5 and 10

In [7]:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[6.93215229 5.67948088 6.71794288]
 [8.99254858 7.9202401  8.23724783]
 [6.72065903 7.24425327 8.74137946]
 [7.82044318 7.12272724 9.36852964]
 [9.23667156 6.74156681 7.41111927]]
